// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: flaco_grpc/flaco.proto

package flaco_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DayServiceClient is the client API for DayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DayServiceClient interface {
	SendDayInfoToServer(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type dayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDayServiceClient(cc grpc.ClientConnInterface) DayServiceClient {
	return &dayServiceClient{cc}
}

func (c *dayServiceClient) SendDayInfoToServer(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/DayService/SendDayInfoToServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DayServiceServer is the server API for DayService service.
// All implementations must embed UnimplementedDayServiceServer
// for forward compatibility
type DayServiceServer interface {
	SendDayInfoToServer(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedDayServiceServer()
}

// UnimplementedDayServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDayServiceServer struct {
}

func (UnimplementedDayServiceServer) SendDayInfoToServer(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDayInfoToServer not implemented")
}
func (UnimplementedDayServiceServer) mustEmbedUnimplementedDayServiceServer() {}

// UnsafeDayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DayServiceServer will
// result in compilation errors.
type UnsafeDayServiceServer interface {
	mustEmbedUnimplementedDayServiceServer()
}

func RegisterDayServiceServer(s grpc.ServiceRegistrar, srv DayServiceServer) {
	s.RegisterService(&DayService_ServiceDesc, srv)
}

func _DayService_SendDayInfoToServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayServiceServer).SendDayInfoToServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DayService/SendDayInfoToServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayServiceServer).SendDayInfoToServer(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// DayService_ServiceDesc is the grpc.ServiceDesc for DayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DayService",
	HandlerType: (*DayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendDayInfoToServer",
			Handler:    _DayService_SendDayInfoToServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flaco_grpc/flaco.proto",
}
